### ISSUE TITLE
Not working on any Gitbook repository

### ISSUE THREAD

**Issue by ajmeese7** [ZanderZhao/gitbook-action#10]
Even when I forked this repository and ran the action, I got the following error messages and the build failed:

```
info: installing plugin "sitemap-general" 
info: install plugin "sitemap-general" (git+https://github.com/plugins-zander/gitbook-plugin-sitemap-general.git) from NPM with version git+https://github.com/plugins-zander/gitbook-plugin-sitemap-general.git
/github/home/.gitbook/versions/3.2.3/node_modules/npm/node_modules/aproba/index.js:25
    if (args[ii] == null) throw missingRequiredArg(ii)
                          ^
Error: Missing required argument #1
    at andLogAndFinish (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:31:3)
    at fetchPackageMetadata (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:51:22)
    at resolveWithNewModule (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/install/deps.js:490:12)
    at /github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/install/deps.js:491:7
    at /github/home/.gitbook/versions/3.2.3/node_modules/npm/node_modules/iferr/index.js:13:50
    at /github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:37:12
    at addRequestedAndFinish (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:67:5)
    at returnAndAddMetadata (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:121:7)
    at pickVersionFromRegistryDocument (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:138:20)
    at /github/home/.gitbook/versions/3.2.3/node_modules/npm/node_modules/iferr/index.js:13:50 {
  code: 'EMISSINGARG'
}
+ gitbook build --gitbook=
info: 11 plugins are installed 
Error: Couldn't locate plugins "sitemap-general, gtag, chapter-fold, copy-code-button", Run 'gitbook install' to install plugins from registry.
+ [ 1 -eq 0 ]
+ print_error 3105: gitbook build failed, please check is there something wrong with your book.json
+ echo \033[31m ERROR 3105: gitbook build failed, please check is there something wrong with your book.json  \033[0m \a \n 
 ERROR 3105: gitbook build failed, please check is there something wrong with your book.json    
+ echo \033[32m Find Detail From: https://zanderzhao.github.io/gitbook-action/error \033[0m
+ exit 1
 Find Detail From: https://zanderzhao.github.io/gitbook-action/error
```

It doesn't matter what the configuration or plugins are, with another repository I got the following error still:

```
info: install plugin "sitemap" (*) from NPM with version 1.2.0 
/github/home/.gitbook/versions/3.2.3/node_modules/npm/node_modules/aproba/index.js:25
    if (args[ii] == null) throw missingRequiredArg(ii)
                          ^
Error: Missing required argument #1
    at andLogAndFinish (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:31:3)
    at fetchPackageMetadata (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:51:22)
    at resolveWithNewModule (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/install/deps.js:490:12)
    at /github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/install/deps.js:491:7
    at /github/home/.gitbook/versions/3.2.3/node_modules/npm/node_modules/iferr/index.js:13:50
    at /github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:37:12
    at addRequestedAndFinish (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:67:5)
    at returnAndAddMetadata (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:121:7)
    at pickVersionFromRegistryDocument (/github/home/.gitbook/versions/3.2.3/node_modules/npm/lib/fetch-package-metadata.js:138:20)
    at /github/home/.gitbook/versions/3.2.3/node_modules/npm/node_modules/iferr/index.js:13:50 {
  code: 'EMISSINGARG'
}
+ gitbook build --gitbook=
info: 7 plugins are installed 
info: 10 explicitly listed 
Error: Couldn't locate plugins "sitemap, alerts, edit-link, codepen", Run 'gitbook install' to install plugins from registry.
+ [ 1 -eq 0 ]
 Find Detail From: https://zanderzhao.github.io/gitbook-action/error
+ print_error 3105:gitbook built fail,please check is there something wrong with your book.json or others
+ echo \033[31m ERROR 3105:gitbook built fail,please check is there something wrong with your book.json or others  \033[0m \a \n 
 ERROR 3105:gitbook built fail,please check is there something wrong with your book.json or others    
+ echo \033[32m Find Detail From: https://zanderzhao.github.io/gitbook-action/error \033[0m
+ exit 1
```

**Comment by ZanderZhao** [comment]
Sorry, I have not solved this problem for now, I think it may be a plugin version compatibility problem, I tried to remove the plugin gitbook-plugin-sitemap-general to some extent to avoid the occurrence of running errors.
